# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4f54a1caa93800afa5d8073fa914bb31c183dd5afdea5f8f44b14170311a6ce3725899094af8f1118bb90162ce2f90c25ee80256795233aef8c644a01294ce9

test:
  secret_key_base: 4a89357744e1b7a72da26a68a10698cbb9662282afb5e472ec060a5e35cc058d5e3d02433386aa382810ee463ed924d98b850c1c85e59e4677c1df0e4eb18369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_ELOS"] %>
